version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
    open-pull-requests-limit: 5
    labels:
      - "Tech-Debt"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:30"
    open-pull-requests-limit: 5
    labels:
      - "Tech-Debt"
    commit-message:
      prefix: "ci"
      include: "scope"
